AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  NestJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: nestjs:latest
      Timeout: 30 
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY