export const data = [
  {
    title: "Oppenheimer",
    year: "2023",
    rated: "R",
    released: "21 Jul 2023",
    runtime: "180 min",
    genre: "Biography, Drama, History",
    director: "Christopher Nolan",
    writer: "Christopher Nolan, Kai Bird, Martin Sherwin",
    actors: "Cillian Murphy, Emily Blunt, Matt Damon",
    plot: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    language: "English, German, Italian",
    country: "United States, United Kingdom",
    awards: "Won 7 Oscars. 344 wins & 358 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg",
    ratings: [
      { Source: "Internet Movie Database", Value: "8.3/10" },
      { Source: "Rotten Tomatoes", Value: "93%" },
      { Source: "Metacritic", Value: "88/100" },
    ],
    metascore: "88",
    imdbRating: "8.3",
    imdbVotes: "716,104",
    imdbID: "tt15398776",
    type: "movie",
    dvd: "21 Nov 2023",
    boxOffice: "$329,862,540",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    title: "Blade Runner 2049",
    year: "2017",
    rated: "R",
    released: "06 Oct 2017",
    runtime: "164 min",
    genre: "Action, Drama, Mystery",
    director: "Denis Villeneuve",
    writer: "Hampton Fancher, Michael Green, Philip K. Dick",
    actors: "Harrison Ford, Ryan Gosling, Ana de Armas",
    plot: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    language: "English, Finnish, Japanese, Hungarian, Russian, Somali, Spanish",
    country: "United States, United Kingdom, Canada, Spain",
    awards: "Won 2 Oscars. 100 wins & 163 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg",
    ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "88%" },
      { Source: "Metacritic", Value: "81/100" },
    ],
    metascore: "81",
    imdbRating: "8.0",
    imdbVotes: "664,542",
    imdbID: "tt1856101",
    type: "movie",
    dvd: "26 Dec 2017",
    boxOffice: "$92,071,675",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    title: "Barbie",
    year: "2023",
    rated: "PG-13",
    released: "21 Jul 2023",
    runtime: "114 min",
    genre: "Adventure, Comedy, Fantasy",
    director: "Greta Gerwig",
    writer: "Greta Gerwig, Noah Baumbach",
    actors: "Margot Robbie, Ryan Gosling, Issa Rae",
    plot: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    language: "English, Spanish",
    country: "United States, United Kingdom",
    awards: "Won 1 Oscar. 193 wins & 420 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    ratings: [
      { Source: "Internet Movie Database", Value: "6.8/10" },
      { Source: "Rotten Tomatoes", Value: "88%" },
      { Source: "Metacritic", Value: "80/100" },
    ],
    metascore: "80",
    imdbRating: "6.8",
    imdbVotes: "535,851",
    imdbID: "tt1517268",
    type: "movie",
    dvd: "12 Sep 2023",
    boxOffice: "$636,238,421",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    title: "Inception",
    year: "2010",
    rated: "PG-13",
    released: "16 Jul 2010",
    runtime: "148 min",
    genre: "Action, Adventure, Sci-Fi",
    director: "Christopher Nolan",
    writer: "Christopher Nolan",
    actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    language: "English, Japanese, French",
    country: "United States, United Kingdom",
    awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,547,638",
    imdbID: "tt1375666",
    type: "movie",
    dvd: "20 Jun 2013",
    boxOffice: "$292,587,330",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    title: "Interstellar",
    year: "2014",
    rated: "PG-13",
    released: "07 Nov 2014",
    runtime: "169 min",
    genre: "Adventure, Drama, Sci-Fi",
    director: "Christopher Nolan",
    writer: "Jonathan Nolan, Christopher Nolan",
    actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    language: "English",
    country: "United States, United Kingdom, Canada",
    awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "73%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    metascore: "74",
    imdbRating: "8.7",
    imdbVotes: "2,113,545",
    imdbID: "tt0816692",
    type: "movie",
    dvd: "24 May 2016",
    boxOffice: "$188,020,017",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    title: "The Martian",
    year: "2015",
    rated: "PG-13",
    released: "02 Oct 2015",
    runtime: "144 min",
    genre: "Adventure, Drama, Sci-Fi",
    director: "Ridley Scott",
    writer: "Drew Goddard, Andy Weir",
    actors: "Matt Damon, Jessica Chastain, Kristen Wiig",
    plot: "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive and can survive until a potential rescue.",
    language: "English, Mandarin",
    country: "United States, United Kingdom, Hungary, Jordan",
    awards: "Nominated for 7 Oscars. 40 wins & 199 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg",
    ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "91%" },
      { Source: "Metacritic", Value: "80/100" },
    ],
    metascore: "80",
    imdbRating: "8.0",
    imdbVotes: "924,576",
    imdbID: "tt3659388",
    type: "movie",
    dvd: "22 Dec 2015",
    boxOffice: "$228,433,663",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
];
